##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  sms配置  ###################
bmac:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: true #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  busposfirmware-path: /opt/cc/sms/uploads/ #固件文件目录
  busposfirmware-url: http://bmac.izit.cn:20028/uploads/ #固件下载地址
  bn-url: http://172.16.7.61:19001/dataComeFromSms?pltSsn= #调用bn模块的扣款地址
#  busposfirmware-path: /opt/cc/sit/s201711211118/apache-tomcat-7.0.82/webapps/examples/ #固件文件目录
#  busposfirmware-url: http://58.118.13.68:20023/examples/ #固件下载地址
#  bn-url: http://127.0.0.1:19001/dataComeFromSms?pltSsn= #调用bn模块的扣款地址
###################  项目启动端口  ###################
server:
  port: 80
  ## sit147 20021

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false


###################  spring配置  ###################
spring:
  redis:
    host: localhost
    port: 6379
    password:
  profiles:
    active: buff
    # produce dev sit(105) test sit147
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/bmac/ffan/**/mapping/*.xml
  typeAliasesPackage: com.bmac.ffan.common.persistence.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

---
##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: buff
  datasource:
      url: jdbc:mysql://192.168.56.4:3306/cc_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: buff
      password: 123456
      filters: log4j,wall,mergeStat

#多数据源
ffan:
  muti-datasource:
    default-dataSource-name: dataSourceGuns #默认的数据源名称
    url: jdbc:mysql://192.168.1.106:3306/cc_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Bmac@#@!123

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: sms.log

scheme:
  job:
     timingUpdateNonCommunicationEquipment: '10 0/30 5-23 * * ?'
     timingParseCenterFile: '10 30 04 * * ?'
  posconfig:
     #单位秒
     posTimeoutIntervalTime: 1800

  ftp:
     ftpPath: /home/ftpuser/
     ftpServerIp: 192.168.1.106
     ftpServerPort: 21
     ftpServerUser: ftpuser
     ftpServerPassWord: bmac1234
     localPath: E://download//

---
##########################################################
###################  开发环境的sit147  ###################
##########################################################
spring:
  profiles: sit147
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/cc_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: bmac123456
      filters: log4j,wall,mergeStat

#多数据源
ffan:
  muti-datasource:
    default-dataSource-name: dataSourceGuns #默认的数据源名称
    url: jdbc:mysql://192.168.1.106:3306/cc_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Bmac@#@!123

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: sms.log

scheme:
  job:
     timingUpdateNonCommunicationEquipment: '10 0/30 5-23 * * ?'
     timingParseCenterFile: '10 30 04 * * ?'
  posconfig:
     #单位秒
     posTimeoutIntervalTime: 1800

  ftp:
     ftpPath: /home/ftpuser/
     ftpServerIp: 192.168.1.106
     ftpServerPort: 21
     ftpServerUser: ftpuser
     ftpServerPassWord: bmac1234
     localPath: E://download//
---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://192.168.2.108:3306/cc_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: bmac123456
#      url: jdbc:mysql://127.0.0.1:33060/cc_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#      username: bmac_cc
#      password: mFvLUrL5iFfE
      filters: log4j,wall,mergeStat

#多数据源
ffan:
  muti-datasource:
    default-dataSource-name: dataSourceGuns #默认的数据源名称
    url: jdbc:mysql://192.168.1.106:3306/cc_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Bmac@#@!123

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: sms.log
  
scheme:
  job:
     timingUpdateNonCommunicationEquipment: '10 0/30 5-23 * * ?'
     timingParseCenterFile: '10 30 04 * * ?'
  posconfig:
     #单位秒
     posTimeoutIntervalTime: 1800
     
  ftp:
     ftpPath: /home/ftpuser/
     ftpServerIp: 192.168.1.106
     ftpServerPort: 21
     ftpServerUser: ftpuser
     ftpServerPassWord: bmac1234
     localPath: E://download//
     
---
##########################################################
###################  集成测试环境的profile  ###################
##########################################################
spring:
  profiles: test
  datasource:
      url: jdbc:mysql://192.168.1.106:3306/cc_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: Bmac@#@!123
      filters: log4j,wall,mergeStat

#多数据源
ffan:
  muti-datasource:
    default-dataSource-name: dataSourceGuns #默认的数据源名称
    url: jdbc:mysql://192.168.1.106:3306/cc_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Bmac@#@!123

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: sms.log

---

##########################################################
###################  集成测试环境的profile  ###################
##########################################################
spring:
  profiles: sit
  datasource:
      url: jdbc:mysql://192.168.1.110:3306/cc_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: bmac123456
      filters: log4j,wall,mergeStat

#多数据源
ffan:
  muti-datasource:
    default-dataSource-name: dataSourceGuns #默认的数据源名称
    url: jdbc:mysql://127.0.0.1:3306/biz?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: sms.log

scheme:
  job:
     timingUpdateNonCommunicationEquipment: '10 0/30 5-23 * * ?'
     timingParseCenterFile: '10 * * * * ?'
  posconfig:
     #单位秒
     posTimeoutIntervalTime: 1800
     
  ftp:
     ftpPath: /home/ftpuser/
     ftpServerIp: 192.168.1.106
     ftpServerPort: 21
     ftpServerUser: ftpuser
     ftpServerPassWord: bmac1234
     localPath: E://download//
---

##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://172.16.7.63:13306/cc_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: bmac_cc
      password: mFvLUrL5iFfE
      filters: log4j,wall,mergeStat

logging:
  level.root: warn
  path: logs/
  file: sms.log

scheme:
  job:
     timingUpdateNonCommunicationEquipment: '10 0/30 5-23 * * ?'
     timingParseCenterFile: '10 05 * * * ?'
  posconfig:
     posTimeoutIntervalTime: 1800 
     
  ftp:
     ftpPath: /downcloudbak/
     ftpServerIp: 172.20.22.33
     ftpServerPort: 21
     ftpServerUser: icloud
     ftpServerPassWord: icloud0504
     localPath: /opt/cc/download/